### ISSUE TITLE
Investigate AWS API Gateway + Lambda

### ISSUE THREAD

**Issue by farski** [PRX/upload.prx.org#6]
- No server
- No app
- Super simple
- Pay per request

**Comment by farski** [comment]
Cons
- deployment of Lambda is a little funky
- not sure if cfn or anything can template APIG yet, so it's a little hard to replicate the environment
- local testing
- standard TLS is $$$
- No ENV variables

**Comment by farski** [comment]
demo: https://6fzgppd4bk.execute-api.us-east-1.amazonaws.com/prod/signature?to_sign=foo

**Comment by kookster** [comment]
nice!

**Comment by farski** [comment]
This is now using a correctly-credentialed key, so it should be good to hit for actual uploading.
